# Generated by Django 4.1.7 on 2023-05-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('form', models.CharField(blank=True, default=None, max_length=23, null=True)),
                ('sprite', models.ImageField(blank=True, null=True, upload_to='drafter/static/drafter/media/img/poke_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('full_name', models.CharField(max_length=32)),
                ('level', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color_code', models.CharField(default='7f7f7f', max_length=6)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='drafter/static/drafter/media/img/profile_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemons', models.ManyToManyField(blank=True, null=True, to='drafter.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=24)),
                ('ability', models.CharField(max_length=32)),
                ('move_a', models.CharField(max_length=32)),
                ('move_b', models.CharField(max_length=32)),
                ('move_c', models.CharField(max_length=32)),
                ('move_d', models.CharField(max_length=32)),
                ('tera_type', models.CharField(max_length=32)),
                ('nature', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=32)),
                ('ev_Hp', models.IntegerField(default=0)),
                ('ev_Atk', models.IntegerField(default=0)),
                ('ev_Def', models.IntegerField(default=0)),
                ('ev_SpA', models.IntegerField(default=0)),
                ('ev_SpD', models.IntegerField(default=0)),
                ('ev_Spe', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=100)),
                ('iv_Hp', models.IntegerField(default=31)),
                ('iv_Atk', models.IntegerField(default=31)),
                ('iv_Def', models.IntegerField(default=31)),
                ('iv_SpA', models.IntegerField(default=31)),
                ('iv_SpD', models.IntegerField(default=31)),
                ('iv_Spe', models.IntegerField(default=31)),
                ('poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafter.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafter.tier'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemons', models.ManyToManyField(blank=True, null=True, to='drafter.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafter.tier')),
                ('users', models.ManyToManyField(blank=True, null=True, to='drafter.user')),
            ],
        ),
    ]
