# Generated by Django 4.1.7 on 2023-05-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0002_pokemon_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp_totale',
            field=models.BigIntegerField(default=0),
        ),
    ]
